# Generated by Django 4.1.3 on 2022-11-18 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("custom_users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="email",
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
